name: testing github workflows
on: push
jobs:
  Integration-continue:
    name: Demontration CI 
    runs-on: unbuntu-latest

    env:
      STEP1: "Le code vient d'etre pouss√© sur Github"

    steps:
      - name: Etape 1 - Initialisation
        run:
          echo "Demrrage du pipeline d'integration continue"
          echo "STEP= $STEP1"
      - name: Etape 2 - Recuperation du code
        run:
          echo "Rceuperation du code source"
          echo "STEP2= ${{vars.VAR2}}"
      - name: Etape 3 - Build
        run:
          echo ""
      - name: Etape 4 - Test
        run:
          echo ""
      - name: Etape 5 - Packaging
        run:
          echo ""
      - name: Etape 6 - Fin dupipeline
        run:
          echo ""
         
      
      